.codecov.yml
.travis.yml
Cargo.lock
core/src/network/packet/implementation.rs
core/src/prelude.rs
core/src/region.rs
core/src/world/chunk.rs
core/src/world/mod.rs
server/Cargo.toml
server/src/config.rs
server/src/initialhandler.rs
server/src/main.rs
server/src/network.rs

This PR contains the rewrite of the chunk implementation.

Rewrite chunk implementation

---

core/src/save/player_data.rs
server/src/joinhandler.rs
server/src/player/init.rs

Load player inventory from save (#72)

---

README.md

Change binary name in readme

---

core/src/network/packet/implementation.rs
core/src/save/region.rs
core/src/world/chunk.rs

- loading of block-/sky-light data from world saves
- sending block-/sky-light data in ChunkData packets

[WIP] support sky/block light

---

server/src/physics/block_bboxes.rs
server/src/physics/math.rs
server/src/physics/mod.rs

Support bounding boxes for non-cubic blocks

---

server/src/io/worker.rs

If no packets are received for 10 seconds, the client will be disconnected.
Resolves #12.

Implement timeouts

---

server/src/chunk_logic.rs
server/src/entity/broadcast.rs
server/src/entity/mod.rs
server/src/entity/movement.rs
server/src/player/init.rs
server/src/testframework.rs

Fix position sync issues by storing last known positions

---

codegen/src/lib.rs
core/src/entitymeta.rs
core/src/network/packet/implementation.rs
core/src/network/packet/mod.rs
core/src/save/entity.rs
server/src/entity/chunk.rs
server/src/entity/component.rs
server/src/entity/impls/animal/chicken.rs
server/src/entity/impls/animal/cow.rs
server/src/entity/impls/animal/donkey.rs
server/src/entity/impls/animal/horse.rs
server/src/entity/impls/animal/llama.rs
server/src/entity/impls/animal/mod.rs
server/src/entity/impls/animal/mooshroom.rs
server/src/entity/impls/animal/pig.rs
server/src/entity/impls/animal/rabbit.rs
server/src/entity/impls/animal/sheep.rs
server/src/entity/impls/animal/squid.rs
server/src/entity/impls/mod.rs
server/src/entity/metadata.rs
server/src/lib.rs
server/src/physics/component.rs
server/src/physics/entity.rs

Entities implemented:
* chicken
* cow
* donkey
* horse
* llama
* mooshroom
* pig
* rabbit
* sheep
* squid
Checklist:
Obviously, entity AI is not implemented here—so these animals will be static.

Implement various animal entities

---

core/src/network/packet/mod.rs
server/src/game.rs
server/src/lib.rs
server/src/systems.rs
server/src/weather.rs

I'm not quite sure what the preferred structure of this project, ie. where events, broadcaster, and functions should live.

Weather: rain + thunderstorm - no thundering, snowing, and putting out fires

---

server/Cargo.toml
server/src/entity/arrow.rs
server/src/entity/mod.rs
server/src/packet_handlers/digging.rs
server/src/packet_handlers/mod.rs
server/src/packet_handlers/use_item.rs
server/src/physics/math.rs
server/src/player/mod.rs
server/src/systems.rs

Physics for the entity is still a bit weird once it's spawned, however, this code successfully handles spawning the entity when the bow is released.

Add support for shooting arrows

---

Cargo.lock
core/Cargo.toml
core/src/lib.rs
core/src/text.rs
server/src/chat.rs
server/src/packet_handlers/chat.rs

Feedback: Am I going the right direction?

Text API: WIP

---

Cargo.lock
Cargo.toml
core/items/src/lib.rs
core/network/src/packets.rs
core/util/src/positions.rs
server/entity/src/broadcasters/entity_creation.rs
server/entity/src/broadcasters/entity_deletion.rs
server/entity/src/broadcasters/inventory.rs
server/entity/src/broadcasters/item_collect.rs
server/entity/src/broadcasters/metadata.rs
server/test/Cargo.toml
server/test/src/lib.rs
server/test/src/unit.rs

Unit testing framework and improved test coverage

---

Cargo.lock
Cargo.toml
core/text/Cargo.toml
core/text/src/lib.rs
core/text/src/markdown.rs
core/text/src/markdown/lexer.rs
core/text/src/markdown/parser.rs
core/text/src/markdown/parser/events.rs
core/text/src/markdown/translator.rs

Add support for parsing a simple markdown language into TextComponents

Text formatting markup language

---

core/text/src/lib.rs
server/network/src/initial_handler.rs

We should most likely change how disconnects are handle in generally, such that we can support raw json text.

Added propper error message for release mode on failed authentication

---

server/player/src/lib.rs
server/types/src/events.rs
server/util/src/time.rs
server/weather/src/lib.rs

closes #217 
I'm trying to do some small fixes to start.

Send game state before PlayerJoinEvent

---

server/commands/src/impls.rs
server/commands/src/lib.rs

Add /say command

---

server/player/src/packet_handlers/inventory.rs

Adds `number_key` handler for #228

Add number key handler for Click Window packets

---

README.md

To clear up some initial confusion I had when first building from source

Add notice about JDK 8 requirement for compiling

---

core/chunk_map/src/lib.rs
server/player/src/packet_handlers/placement.rs
server/types/src/game.rs

Also improves documentation of block_at and set_block_at
Fixes #292

Prevent panic when trying to place a block at y=256

---

Cargo.lock
codegen/src/lib.rs

I was just skimming through the source and thought I would do this as my first PR haha

reverse the hashmap in codegen

---

server/player/src/packet_handlers/digging.rs

Discussed in #303 and duplicate of #313

Add minimal bow holding time before shooting

---

core/blocks/src/categories.rs

Hey. I noticed that stairs were facing the wrong way when placing them, and this fixed it for me.

Change stairs placement type to PlayerDirection

---

server/entity/src/object/falling_block.rs

Currently, the falling block replaces the non solid block, such as torches and rails, with these changes, the falling block will be dropped as an item in the location it would land, just as it happens in Vanilla.

Drops falling block as item when landing on a non solid block

---

core/network/src/mctypes.rs

This fixes the issue when you write a negative integer and it infinitely loops and leaks. Additionally, I added more tests from wiki.vg

Fix writing negative i32 varints

---

Cargo.lock
core/blocks/src/categories.rs
server/commands/src/arguments.rs
server/commands/src/impls.rs
server/commands/src/lib.rs
server/src/event_handlers.rs
server/types/src/events.rs
server/types/src/game.rs
server/util/src/time.rs

Implements /time command (#229)

Time command

---

server/types/src/game.rs

I noticed two issues with the damage logic:
- an entity is only killed when the damage exceeds it's health, but not if it reaches exactly zero, while it should be considered dead at that point (I assume from the fact that the client shows the death screen at zero health, correct me if I'm wrong here) 
- when changing the threshold to less than one and reaching exactly zero health, the entities health is not updated to the new value before killing (which causes the client not to show a death screen )
EDIT: the second issue of course only occurred when fixing the first

Fix lethal damage edge case

---

crates/base/Cargo.toml
crates/blocks/Cargo.toml
crates/common/Cargo.toml
crates/datapacks/Cargo.toml
crates/ecs/Cargo.toml
crates/generated/Cargo.toml
crates/plugin-host/Cargo.toml
crates/protocol/Cargo.toml
crates/server/Cargo.toml
crates/utils/Cargo.toml
crates/worldgen/Cargo.toml

We have lots of dependencies and the lists were pretty much in random order, so I thought this would add some more organization.
Courtesy of https://github.com/DevinR528/cargo-sort-ck.

Sort dependency lists in Cargo.toml

---

README.md
docs/architecture.md

I hope this helps new contributors. Feedback is appreciated :)

Add basic architectural documentation

---

Cargo.lock
crates/common/Cargo.toml
crates/common/src/events.rs
crates/common/src/events/interact_entity.rs
crates/server/Cargo.toml
crates/server/src/client.rs
crates/server/src/packet_handlers.rs
crates/server/src/packet_handlers/interaction.rs
crates/server/src/systems.rs

Adds an entity interaction event that gets fired when the server gets an entity interact packet. 
This is my first PR on the refactor so let me know if I put code in the wrong places or did anything wrong please.
TODO(?)

Add entity interaction event.

---

crates/plugin-host/src/plugin/native.rs

Hopefully this resolves native plugins not loading on Windows.

Close plugin shared libraries before loading

---

Cargo.lock
crates/server/src/systems.rs

This accidentally got merged in #362.

Remove test disconnect code

---

feather/server/src/initial_handler.rs

The server crashed at executing send_loaded_chunks feather/server/src/systems/view.rs if someone in 1.8. joined.

Fixed server crash when joining with 1.8.

---

Cargo.lock
feather/protocol/src/codec.rs
feather/protocol/src/io.rs
feather/server/Cargo.toml
feather/server/src/config.rs
feather/server/src/connection_worker.rs
feather/server/src/initial_handler.rs
feather/server/src/options.rs

This should resolve a number of performance issues in debug mode.

server: Implement packet compression

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/missing-documentation.md

This adds some issue templates that are going to be useful now that feather is starting to take off! 🚀

Add issue templates

---

libcraft/core/src/dimension.rs
libcraft/core/src/lib.rs

Implemented enum for dimensions
Created the functions to get the `dim_id` and the `namespaced_id`. 
Implemented TryFrom and Into traits, to serialize and deserialize using the `namespaced_id`.
Closes #386

Added dimensions enum.

---

CONTRIBUTING.md
README.md
docs/pull_request_template.md
feather/server/config.toml
tools/proxy/README.md

**README.md**: Corrected a small mistake and highlighted certain parts (aka 2 words)
feather/server/**config.toml**: Highlighted the unimplemented part and added further information
tools/proxy/**README.md**: Updated information and changed port to 25577 (default proxy port)
**CONTRIBUTING.md**: Added further information about contributing (feel free to comment things I should add before merging) and highlighted a warning.
NOTE: My spelling may not be on point

Updated some information provided in the Markdown files

---

feather/common/src/world_source/flat.rs

I improved the flatworld generator/source, by separating code to make it more readable and creating two more layers (e.g. a bedrock layer at the bottom).

Improve FlatWorld generator

---

.github/workflows/main.yml
README.md

_Short description what you did and/or fixed_
Add automatic artifact capturing so people don't download the old version haha
_Leave empty if none_

Add artifact capturing

---

quill/README.md

I just added text and we discussed approval in  the discord.

Add notice to quill readme

---

feather/server/src/config.rs
feather/server/src/main.rs

Fixed logging of config after my previous pr created a small "problem" with the config loading/creating not being logged.

Fix Logging of Config

---

.github/pull_request_template.md
feather/blocks/generator/src/load.rs
feather/server/src/initial_handler.rs
feather/worldgen/src/density_map/density.rs
libcraft/text/src/text/markdown/parser.rs
libcraft/text/src/text/markdown/translator.rs
quill/cargo-quill/src/main.rs

Fixed all warnings clippy threw after updating to latest stable version. Also improved `pull_request_template.md`
#447

Fix clippy warnings and update PR template

---

feather/base/src/anvil/region.rs
feather/base/src/chunk.rs

Fixed my own mistake that prevented the game from loading normal chunks.

Fix chunk loading

---

.github/workflows/main.yml
.github/workflows/release.yml

Using cross for additional targets

GitHub Actions improvements and cross compilation

---

feather/server/src/client.rs

Oh no! #469 and #470 were in conflict and broke the build

Make it build

---

feather/datapacks/vanilla_assets/src/lib.rs

Changed vanilla JAR download timeout, made it const
Added warnings when the network is very slow (with 2, 4, 6, ... minutes timeout). No one will see this because we don't have a logging frontend in feather-datapacks build script. Also, in build scripts, the stdout is only saved to target/debug/build/feather-datapacks-{hash}/output and not displayed on cargo build's stdout (except for cargo build -vv, which shows too much output to find the warning)
#473 

Change vanilla JAR download timeout and add warnings

---

Cargo.lock
feather/base/Cargo.toml
feather/base/src/block.rs
feather/base/src/lib.rs
feather/base/src/metadata.rs
feather/common/src/events/block_change.rs
feather/common/src/game.rs
feather/common/src/world.rs
feather/plugin-host/src/host_calls/block.rs
feather/protocol/src/io.rs
feather/protocol/src/packets.rs
feather/protocol/src/packets/client/play.rs
feather/protocol/src/packets/server/play.rs
feather/server/src/client.rs
feather/server/src/packet_handlers/interaction.rs
libcraft/core/src/positions.rs

Adds `ValidatedBlockPosition` which checks if a block position is valid in order to increase runtime safety. I've updated all internal code to use this type where applicable, 
Closes #476

Add `ValidatedBlockPosition`

---

feather/generated/feather/inventory.json
feather/generated/src/inventory.rs

Adds the missing slot to the player's inventory

Add offhand slot to player inventory

---

feather/server/src/packet_handlers.rs
feather/server/src/packet_handlers/interaction.rs

Implements handling of `SwapItemInHand` status.

Implement swap item in hand

---

feather/base/src/anvil/player.rs
feather/common/src/game.rs
feather/common/src/window.rs
feather/server/src/client.rs
feather/server/src/entities.rs
feather/server/src/systems/entity.rs
feather/server/src/systems/player_join.rs
feather/server/src/systems/player_leave.rs

Fix position syncronization issues for entities and fixes loading and saving of playerdata to use the correct inventory slot indexes
